### ISSUE TITLE
Brain Write and Wire Frame

### ISSUE THREAD

**Issue by shreya-ahujaa** [sonakshibhalla/tri2turtles#76]
- [x] finish the wire frame for the project
- [x] brainstorm some technicals for the project

[Link to Wireframe Folder](https://drive.google.com/drive/folders/1tEqdmcFCcR7MbMvvf6RrQ3N9PC5EiW15?usp=sharing)
[Link to Brainwrite/storm Wiki Page](https://github.com/sonakshibhalla/tri2turtles/wiki/Technical-Ideas-for-Website)

**Comment by PunarvasuS** [comment]
(Link to Wireframe Folder)[https://drive.google.com/drive/folders/1tEqdmcFCcR7MbMvvf6RrQ3N9PC5EiW15?usp=sharing]
