### ISSUE TITLE
Sprint 1 Review

### ISSUE THREAD

**Issue by shreya-ahujaa** [sonakshibhalla/tri2turtles#79]
* Scrum Team Project Review
    - **Design** (Punnu) - Wiki Theme, [Brain Write & Wire Frame](https://github.com/sonakshibhalla/tri2turtles/issues/76)
    - **Technicals** (All)  - [10  to 12 key ideas](https://github.com/sonakshibhalla/tri2turtles/issues/72) 
    - **Github** (Sonakshi) - On Wiki containing [Management Plan](https://github.com/sonakshibhalla/tri2turtles/issues/71)
    - **Deployment** (Khushi) - [Wiki Plan](https://github.com/sonakshibhalla/tri2turtles/issues/77), [Hardware and Frequency](https://github.com/sonakshibhalla/tri2turtles/issues/78)
    - **Scrum Board** (Shreya) - [Assignments](https://github.com/sonakshibhalla/tri2turtles/issues) and [Backlog](https://github.com/sonakshibhalla/tri2turtles/projects/2)
  
* Individual Create Task Understanding and Score, Notes, on TPT
    - TPT 0.0, Create Task ideas, notes, and research
    - 1.3 Program Design and Development - [Shreya/Sonakshi](https://github.com/sonakshibhalla/tri2turtles/issues/69) & [Punnu/Khushi](https://github.com/sonakshibhalla/tri2turtles/issues/70)
    - 1.4 Identifying and Correcting Errors - [Shreya/Sonakshi](https://github.com/sonakshibhalla/tri2turtles/issues/69) & [Punnu/Khushi](https://github.com/sonakshibhalla/tri2turtles/issues/70)

* Grading Plan 

- [x] [Readme Time-box](https://github.com/sonakshibhalla/tri2turtles/blob/main/README.md#week-1-due-122) and Review Ticket required
- [x] Preliminary grading on Friday with Cross Over team, including Review Ticket comments and score per individual.  BOF should review fellow BOF (DOWN BELOW)
- [x] Live grading from Teacher on Th and F, including adjustments based on cross over grading before logging in Gradebook.
- [x] Adjustments to reviews and final message can be sent by EOD Friday.

**Comment by allisonthuang** [comment]
3 Glows:

3 Grows:

Sonakshi:

Shreya:

Khushi:

Punnu:
